export const dataDoArt = [
        {
            artist : 'Carrie Mae Weems',
            imgArtist: 'src/assets/artists/Carrie-Mae-Weems.png',
            typeArt : 'Visual Artist',
            biography: 'Steeped in African American history, Carrie Mae Weems makes alternately searing and tender photographs and videos that explore race, family, class, and gender identity. The artist, who has also worked in verse and performance, embraces activism throughout all her work—in particular, she looks to history in order to better understand the present',
            categories : 'Photography, ' + 'Mixed-media, ' + 'Collage',
            products : [
                {
                    id: 1,
                    imgProdut: 'src/assets/art/Weems-Lewitts-2002.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 213,
                    category : 'Photography',
                    artist : 'Carrie Mae Weems',
                },
                {
                    id: 2,
                    imgProdut: 'src/assets/art/Weems-Mountains-2002.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 213,
                    category : 'Photography',
                    artist : 'Carrie Mae Weems',
                },
                {
                    id: 3,
                    imgProdut: 'src/assets/art/Weems-SomeSaid-1996.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 213,
                    category : 'Photography',
                    artist : 'Carrie Mae Weems',
                }
            ]
        },
        {
            artist : 'Barbara Kruger',
            imgArtist: 'src/assets/artists/Yinka-Shonibare.jpeg',
            typeArt : 'Conceptual Artist',
            biography: 'Steeped in African American history, Carrie Mae Weems makes alternately searing and tender photographs and videos that explore race, family, class, and gender identity. The artist, who has also worked in verse and performance, embraces activism throughout all her work—in particular, she looks to history in order to better understand the present',
            categories : ['Photography', 'Mixed-media', 'Collage'],
            products : [
                {
                    id: 1,
                    imgProdut: 'src/assets/art/Kruger-IShop-1990.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 300,
                    category : 'Photography',
                    artist : 'Barbara Kruger',
                },
                {
                    id: 2,
                    imgProdut: 'src/assets/art/Kruger-Jerk-1990.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 300,
                    category : 'Photography',
                    artist : 'Barbara Kruger',
                }

            ]
        },
        {
            artist : 'Yinka Shonibare',
            imgArtist: 'src/assets/artists/Barbara-Kruger.png',
            typeArt : 'Multidisciplinary Artist',
            biography: 'Steeped in African American history, Carrie Mae Weems makes alternately searing and tender photographs and videos that explore race, family, class, and gender identity. The artist, who has also worked in verse and performance, embraces activism throughout all her work—in particular, she looks to history in order to better understand the present',
            categories : ['Photography', 'Mixed-media', 'Collage'],
            products : [
                {
                    id: 1,
                    imgProdut: 'src/assets/art/Shonibare-Champagne-2013.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 300,
                    category : 'Photography',
                    artist : 'Yinka Shonibare',
                },
                {
                    id: 2,
                    imgProdut: 'src/assets/art/Shonibare-Hybrid-2021.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 300,
                    category : 'Photography',
                    artist : 'Yinka Shonibare',
                },
                {
                    id: 3,
                    imgProdut: 'src/assets/art/Shonibare-Hybrid2-2021.png',
                    nameProduct: 'arte',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 300,
                    category : 'Photography',
                    artist : 'Yinka Shonibare',
                },
                {
                    id: 1,
                    imgProdut: 'src/assets/art/Shonibare-Champagne-2013.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 300,
                    category : 'Photography',
                    artist : 'Yinka Shonibare',
                },
                {
                    id: 1,
                    imgProdut: 'src/assets/art/Shonibare-Champagne-2013.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 300,
                    category : 'Photography',
                    artist : 'Yinka Shonibare',
                },
                {
                    id: 1,
                    imgProdut: 'src/assets/art/Shonibare-Champagne-2013.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 300,
                    category : 'Photography',
                    artist : 'Yinka Shonibare',
                },
                {
                    id: 1,
                    imgProdut: 'src/assets/art/Shonibare-Champagne-2013.png',
                    nameProduct: 'Some Said You Were the Spitting Image of Evil, 1995-1996',
                    dimensions: '67.9 × 57.8 cm',
                    materials: 'Chromogenic print with sandblasted text on glass',
                    description: 'The piece serves as a powerful reflection on the ways in which individuals are often subjected to judgment based on external appearances, urging a deeper understanding of the nuanced layers of human experience',
                    Price: 300,
                    category : 'Photography',
                    artist : 'Yinka Shonibare',
                },
            ]
        }
    ]